language: node_js

sudo: false

branches:
  only:
    - master

node_js:
  - '4'
  - '5'
  - '6'
  - '7'

os:
  - linux
  - osx
 
env:
  - NODE_ENV=testing

cache:
  directories:
    - $HOME/.npm
    - ~/.npm
    - ~/.yarn-cache
    - travis_phantomjs
    - node_modules	
  
script: npm test 
script: npm install -global && cd test && npm install && lcc
