language: node_js

sudo: false

branches:
  only:
    - master

node_js:
  - '7'
  - '8'
  - '9'
  - node

os:
  - linux
  - osx
 
env:
  - NODE_ENV=testing

cache:
  directories:
    - $HOME/.npm
    - ~/.npm
    - ~/.yarn-cache
    - travis_phantomjs
    - node_modules	
  
script: npm test 
script: npm install -global && cd test && npm install && lcc
